### ISSUE TITLE
Training error: "TensorArray has size zero, but element shape <unknown> is not fully defined."

### ISSUE THREAD

**Issue by MrGLaDOS** [abisee/pointer-generator#1] opened 2017-05-02 12:54 UTC
Hello,

After running the code for about half an hour in train mode, the following error stopped the training process:

> TensorArray has size zero, but element shape <unknown> is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.

The error appeared when the code was run with the following parameters:
`CUDA_VISIBLE_DEVICES=5 python run_summarization.py --mode=train --data_path=/path-to-train/train.bin --vocab_path=/path-to-vocab/vocab --log_root=/path-to-log/log --exp_name=myexperiment2 --max_enc_steps=100 --max_dec_steps=50 --lr=0.01`
The error also occurred after some hours when the learning rate was not specified.

The full traceback is provided below:

`Caused by op u'gradients/seq2seq/encoder/bidirectional_rnn/fw/fw/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGatherV3', defined at:
  File "run_summarization.py", line 264, in <module>
    tf.app.run()
  File "/opt/neuralnetworks/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "run_summarization.py", line 250, in main
    setup_training(model, batcher)
  File "run_summarization.py", line 111, in setup_training
    model.build_graph() # build the graph
  File "/local/s1742159/neuralnetworks2017/pointer-generator/model.py", line 298, in build_graph
    self._add_train_op()
  File "/local/s1742159/neuralnetworks2017/pointer-generator/model.py", line 274, in _add_train_op
    gradients = tf.gradients(loss_to_minimize, tvars, aggregation_method=tf.AggregationMethod.EXPERIMENTAL_TREE)
  File "/opt/neuralnetworks/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 560, in gradients
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/opt/neuralnetworks/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 368, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/opt/neuralnetworks/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 560, in <lambda>
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/opt/neuralnetworks/lib/python2.7/site-packages/tensorflow/python/ops/tensor_array_grad.py", line 186, in _TensorArrayScatterGrad
    grad = g.gather(indices)
  File "/opt/neuralnetworks/lib/python2.7/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 328, in gather
    element_shape=element_shape)
  File "/opt/neuralnetworks/lib/python2.7/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 2244, in _tensor_array_gather_v3
    element_shape=element_shape, name=name)
  File "/opt/neuralnetworks/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/opt/neuralnetworks/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/opt/neuralnetworks/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

...which was originally created as op u'seq2seq/encoder/bidirectional_rnn/fw/fw/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3', defined at:
  File "run_summarization.py", line 264, in <module>
    tf.app.run()
[elided 2 identical lines from previous traceback]
  File "run_summarization.py", line 111, in setup_training
    model.build_graph() # build the graph
  File "/local/s1742159/neuralnetworks2017/pointer-generator/model.py", line 295, in build_graph
    self._add_seq2seq()
  File "/local/s1742159/neuralnetworks2017/pointer-generator/model.py", line 199, in _add_seq2seq
    enc_outputs, fw_st, bw_st = self._add_encoder(emb_enc_inputs, self._enc_lens)
  File "/local/s1742159/neuralnetworks2017/pointer-generator/model.py", line 74, in _add_encoder
    (encoder_outputs, (fw_st, bw_st)) = tf.nn.bidirectional_dynamic_rnn(cell_fw, cell_bw, encoder_inputs, dtype=tf.float32, sequence_length=seq_len, swap_memory=True)
  File "/opt/neuralnetworks/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 350, in bidirectional_dynamic_rnn
    time_major=time_major, scope=fw_scope)
  File "/opt/neuralnetworks/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 553, in dynamic_rnn
    dtype=dtype)
  File "/opt/neuralnetworks/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 671, in _dynamic_rnn_loop
    for ta, input_ in zip(input_ta, flat_input))
  File "/opt/neuralnetworks/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 671, in <genexpr>
    for ta, input_ in zip(input_ta, flat_input))
  File "/opt/neuralnetworks/lib/python2.7/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 381, in unstack
    indices=math_ops.range(0, num_elements), value=value, name=name)
  File "/opt/neuralnetworks/lib/python2.7/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 409, in scatter
    name=name)
  File "/opt/neuralnetworks/lib/python2.7/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 2510, in _tensor_array_scatter_v3
    name=name)
  File "/opt/neuralnetworks/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)

UnimplementedError (see above for traceback): TensorArray has size zero, but element shape <unknown> is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
         [[Node: gradients/seq2seq/encoder/bidirectional_rnn/fw/fw/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@seq2seq/encoder/bidirectional_rnn/fw/fw/TensorArray_1"], dtype=DT_FLOAT, element_shape=<unknown>, _device="/job:localhost/replica:0/task:0/gpu:0"](gradients/seq2seq/encoder/bidirectional_rnn/fw/fw/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGrad/TensorArrayGradV3, seq2seq/encoder/bidirectional_rnn/fw/fw/TensorArrayUnstack/range, gradients/seq2seq/encoder/bidirectional_rnn/fw/fw/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGrad/gradient_flow)]]
         [[Node: seq2seq/output_projection/Softmax_24/_3175 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_5326_seq2seq/output_projection/Softmax_24", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]`

**Comment by abisee** [comment] 2017-05-02 18:23
Hi MrGLaDOS,

I've seen this myself sometimes. Usually I just restart training and it continues without issue. I'm afraid I don't know what causes it (looks like something with tf.nn.bidirectional_dynamic_rnn?). Sorry not to be of more help.

**Comment by hate5six** [comment] 2017-05-03 02:40
@MrGLaDOS I just ran into the same problem. I resumed training as per @abisee's suggestion and so far it seems to be running again

**Comment by StevenLOL** [comment] 2017-05-03 06:18
Same here, 100% appears in training.

**Comment by liuchen11** [comment] 2017-05-03 10:31
Same problem +1

**Comment by bugtig** [comment] 2017-05-04 01:26
Got the same problem as well. 
Like @abisee said, it is coming from the dynamic_rnn call inside bidirectional dynamic rnn of the encoder.
IIRC, the tensorarray is how the function makes a dynamic length backproppable array in the graph, so if it's size zero it would suggest there is something happening with the input, maybe an empty string input or something. I think it should be debuggable, but I'm also not seeing the error for a while now after restarting. It seems quite random.

**Comment by bugtig** [comment] 2017-05-04 01:29
UPDATE:
So I just checked my log with two tf.Print running each on the encoder dynamic rnn tensor array size and encoder_input and I see

I tensorflow/core/kernels/logging_ops.cc:79] []
I tensorflow/core/kernels/logging_ops.cc:79] [0]
I tensorflow/core/kernels/logging_ops.cc:79] [0]
W tensorflow/core/framework/op_kernel.cc:993] Unimplemented: TensorArray has size zero, but element shape <unknown> is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.

whereas normally it is 

I tensorflow/core/kernels/logging_ops.cc:79] [[[-6.0314578e-05 0.00017527914 -2.7157696e-05 ...
I tensorflow/core/kernels/logging_ops.cc:79] [40]
I tensorflow/core/kernels/logging_ops.cc:79] [40]

It seems that it is caused by an empty encoder input. 
I have not cheked the data but is it possible it contains empty lines?

**Comment by abisee** [comment] 2017-05-04 02:09
@bugtig Thanks, you're right.

If you look at the `cnn/stories` and `dailymail/stories` directories you might have downloaded from [here](http://cs.nyu.edu/~kcho/DMQA/), you'll find that some files, e.g. `cnn/stories/72aba2f58178f2d19d3fae89d5f3e9a4686bc4bb.story`, have an empty article (but they do have the reference summary seemingly correct). 

If you followed the instructions [here](https://github.com/abisee/cnn-dailymail) to generate the `.bin` files, you will therefore have some examples with empty article text. I ran a quick check and found that there are 114 such examples in `train.bin`, and none in `val.bin` or `test.bin`. This is most likely what's causing the error.

For now, a quick fix is to throw out empty article text before it gets batched. I'll do this now.

**Comment by hate5six** [comment] 2017-05-04 02:13
I just finished my analysis right before @abisee's findings and can confirm there are 114 empty articles. Here are the ids:

a460c7560b149c25fd89f46115b8a7865b4b1062.story
6ce5c33e786e149d50e78aeadc5cf449e6da09ce.story
59552b2a2e96a618d5bffbece2849438aa5d4ce1.story
6972eff7e00f5c5b8bc864de2db115f31d53df61.story
63951f504244c71e2e821c7780643b56e103145c.story
f3e35fbb7821204344e8f40336f68bd5a396e330.story
325a0a28b647358e32731e174d5bcd2a7179f6bf.story
d444271ebb079b8f78c34197bfbcf87ae5a41129.story
a2a2ff9da575558d8d8544d0726b9a1c2aa20203.story
1efddd4caf41c8ecabbc6534b7ee38518c11f481.story
ce3271caecf540a64b4ae1b5943194ee1084b712.story
b750310e3a3537e2324539a055424849377bad66.story
fa65f3da733c62eabd0fef3af46a3e71006f94e8.story
ad68b7fcf4f629c048d0367afab738ea1252e78e.story
72855376efdaa110e598e17d36aaa5a46ed14425.story
ef65cc0a69ac25f86c5fa94354ae3b2b71aec3f4.story
e637d817aaf0a8df2e52ef9beed6b2abd33324f3.story
5f84ad5a9258b6620f9a1f7707af68d7980763d3.story
5652311e3db90786c75f994a1803e1d9eb8fb595.story
4f61c32c9f68551fa37f1ba9e0ac8eb3183c2f9f.story
d694a384c370848ffaac9ec9c64362b4dbaa4056.story
f40905e6c4222e41e0ce8c3a58173bc08afd4ee9.story
f7a82862d878453c968f343c1cc128695b33e78d.story
c36fb222cee4c1f4e38cf62ad37e2eb8dd0a85be.story
e302c9577379867f809dcf5bb81ef4cd4981e670.story
fb2de39e76598a7df3fc83586bc8e8b76ee66000.story
feda63ce911f8523fb191b5038377de670d7deae.story
c9d5ec30c9e88efebf792a243a064f9173312ef3.story
118e01697b58e37f56bd03004a608a6b3126e384.story
7fa8a466d78b5232c91feceae35025b4c190e049.story
13abd3e35628071686b33a3b9201cd09da4e1a01.story
4a524c9714a5651a5f02497d23a8164f868babcd.story
5d221a50d10208b82177cd2b92ccd83dd6b9a501.story
200dc5cb7d6a675fc527b9b8d8d6b9c4223f9a95.story
72aba2f58178f2d19d3fae89d5f3e9a4686bc4bb.story
aa90a73e5663c5a0563411da4538b4cabf225528.story
556de3fae14f7e33cc8b97805213049423155b54.story
17201d7e00b4227c985c8dd6ce80c925865d4720.story
9d37272018e78cc2c08a03d0785134751559113f.story
9860d928e14347953050d94320165221e6a13b9c.story
17c0b96f8b303bcf8ae6d4fc3f9776e535805d4f.story
7ccc6f78ca5a895e729e10dbcd46a361eda88370.story
e5509455d119c584a808ed400a875b9866a5760c.story
7d7f347f8bff07d5a3c071e321f3b8747525558e.story
8f9eabb8b4c50b7ec02943b27b172bf63058ae37.story
9a43998000a5ccd2c601ab3d4ee737f94fa1dd3f.story
2cb398794fea7b2dd83501c401c034ca73362323.story
c4019c2d8811a0dce6111ca901e8f87dfd12d1ed.story
6e782862e65a315c67f8de9b6c6d0b4de21a6126.story
2ea9af851da7da8e53247253f2c17425650f7aeb.story
00465603227f7f56fcd37e10f4cd44e57d7647d8.story
47e8e99e7142974b06d6ca7184fcf84f4ac417de.story
cfa9c2b6ef031670fc61f17a386836ec6b2e6c2d.story
d49fae80783e17fd19776cc5e726eb7074c82821.story
4b6e5184eadd3837a6f488cc02230bd4ac08c9cb.story
2dc5e01db66fa12817c2f4913f70db1d519604df.story
07bca124a8b784800aa38e6237524eb756792c7c.story
5bb46b196aebdef40d69305d66edb849fd1ab0e1.story
3b522b0f65c9f2b0f57b6158a9363706cf4093c4.story
84b530bc2b81c7f6b917906e0f6fc6dec87d4e8e.story
d79f84285d756ff2f2837f2537f446a3dc77e531.story
b2b5d58df498c2cd9fdd7d85a593d9723af5b8a1.story
252a4b88464ec3219f3a541f3a87dc34c2d176c0.story
a3b6e7cc664dc625625c52c1c75065f4d64fdf59.story
158501546d04c78797fe4aa887540514469fa87d.story
226ca83313bb4db0917847f80fcf4a2d2af5007d.story
b5cf3c7ca910ef126f4f090421af860e8b16e598.story
9405f6cd3c08cb4232e255a8a0f940bd3fafd1d5.story
0de44dd3a66327f990e4f21b2c672424a07dbfb7.story
50b9ecc13e205f4fde650e2cf46af980b805f5ce.story
a57bddf79c4f96d69701a27d50cf17cd032d1c7a.story
a188c6c37efedf75d6fed22b163384ed06159985.story
fe679e0c6630a794a04a40e5b892e024dbf860fe.story
a25f9cb21da1f59d6b8999cc11aedd0a9f4d4c7a.story
1a00c87c9d1d192f103d6ccf2ad76062f2229609.story
a3725da94f0abe3dd115c8b4ca2f300f8fec2f5e.story
1a918e011f1952ed5c37c48c0b5f7350f804f865.story
62afb1f0c48eb670641f26fadc82b09c34ed6d9d.story
d4b4ee22583e0490d5e41e93941e8e6ec182d7ab.story
66a28ddaceb55e3f7b2777522f3c1062237cb25f.story
a31c3eea301a7347b3f5add677c2d131f962e983.story
3d78806f43f1d7d4aac43f12d2fa6450d3e7c734.story
d91e44938337b408add4f1526811ac6e3258e570.story
c08fb8961d12365b11a8af63fad93219d607f8b7.story
abb74e2466084a9968a305ac439229302e5de164.story
fc1a99c9e7171a3ac1e3be97fae1fc34b0fa2c9e.story
23b70ea2a46e6a9abbe4e46c0d80088c76f6a0af.story
7e94c09d00811e544d2d87deacc98b11de685cda.story
edee4665e5bd44bf184218f870d3db7bbc56a24b.story
3b61e966c25eb515ad82e5c51d78220b2a9a1f79.story
a2dbee50cac09763a3c2bb2967f4c845e378feab.story
bab4d871c260eb84f1fc26aa7144ab202536bc70.story
97be96d338ad91149bbf6c6376675f8d74bf2ac9.story
59509e92b7cf482e8717549585cbd9b9b9a4d9f2.story
b584f48a1ca687e1a4092403478fccf9e49f38f5.story
1963afbc839123244fa3c483b7d5256bf057f758.story
fc7d6be6a3591ae1647324ed31e07245b9835b6c.story
fe9b7daaab79553adaea3e9aa086510bca4b1fb3.story
97bb70b3837cff47e258c3ddf3aba494e6f4a139.story
5bd1db164dad9a37333f952502f65ce3d285534a.story
f8de6d76c2ca4c519e5835ce7bee9175bb2bbd5f.story
a548421e8517a8d92240bc09249776c051cdd392.story
09ac649da7f5ae27d3a7ef47eeb9b8ea4cbd799c.story
ac10b63f389ac2b694b7e7ca48eb5a35e8dd82fd.story
85ae2133c0eb01a1cf6dc762b76b2bf5c0303a5b.story
bc8c6a91d9a3b37f5175a6ee52afdd5857c1accf.story
5dd9aaaca2b6ef805f4d8c50ea042e805fa427a6.story
3135481259a4abea442463b5085d9b18c0665168.story
f2df67d1f4e67f8feff519039b9a424933d82655.story
6bb512326b18c236aca8d2de2633eae28fd3cb86.story
cf0c6788b92a287cccc4523776a442469796c4a8.story
15e1efd925d246b6a93cda25fc3677e923081722.story
ee2db1f51d7d77ca6b449668f256b78762645390.story
3374e475b259036b025c137c7947b4a4305ad514.story

**Comment by abisee** [comment] 2017-05-04 02:23
OK, I've now committed a change to `batcher.py` so examples with empty article text are now discarded. Hopefully this should fix the problem.

**Comment by scylla** [comment] 2017-05-08 04:31
Thanks was facing the same issue.

**Closed** 2017-06-06 16:36 UTC

**Comment by mar71ns** [comment] 2018-06-30 14:39
python3 train-autoencoder.py -n 128 -u 256 -r 0.001 -b 16 -e 5 -d 0.9 -i 50 --mono ./modelTrip ./modelTrip/vocabulary.txt ./modelTrip/train-data.npz ./modelTrip/valid-data.npz

/home/dpi/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-06-30 11:38:15.134550: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-06-30 11:38:15.134889: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: GeForce GTX 1050 major: 6 minor: 1 memoryClockRate(GHz): 1.455
pciBusID: 0000:01:00.0
totalMemory: 1.95GiB freeMemory: 1.66GiB
2018-06-30 11:38:15.134916: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-06-30 11:38:15.278670: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-06-30 11:38:15.278695: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2018-06-30 11:38:15.278716: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2018-06-30 11:38:15.278831: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1422 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050, pci bus id: 0000:01:00.0, compute capability: 6.1)
INFO:root:Reading training data
INFO:root:Reading validation data
INFO:root:Creating model
WARNING:tensorflow:From /home/dpi/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_impl.py:1344: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See @{tf.nn.softmax_cross_entropy_with_logits_v2}.

WARNING:tensorflow:From /home/dpi/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_impl.py:1344: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See @{tf.nn.softmax_cross_entropy_with_logits_v2}.

autoencoder/embeddings:0: (11123, 128) (1423744 parameters)
autoencoder/lstm_cell/kernel:0: (384, 1024) (393216 parameters)
autoencoder/lstm_cell/bias:0: (1024,) (1024 parameters)
projection/dense/kernel:0: (256, 11123) (2847488 parameters)
projection/dense/bias:0: (11123,) (11123 parameters)
Total: 4676595 parameters
INFO:root:Initialized the model and all variables. Starting training.
Traceback (most recent call last):
  File "/home/dpi/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/home/dpi/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/dpi/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnimplementedError: TensorArray has size zero, but element shape <unknown> is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: gradients/autoencoder/autoencoder/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGatherV3 = TensorArrayGatherV3[dtype=DT_FLOAT, element_shape=<unknown>, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/autoencoder/autoencoder/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGrad/TensorArrayGradV3, autoencoder/autoencoder/TensorArrayUnstack/range, gradients/autoencoder/autoencoder/while/TensorArrayReadV3/Enter_1_grad/b_acc_3)]]
	 [[Node: truediv/_111 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1957_truediv", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train-autoencoder.py", line 113, in <module>
    args.dropout_keep, 5.0, report_interval=args.interval)
  File "/home/dpi/Documentos/Gustavo/autoencoder/src/autoencoder.py", line 257, in train
    _, loss = session.run([self.train_op, self.loss], feeds)
  File "/home/dpi/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/dpi/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/dpi/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/dpi/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnimplementedError: TensorArray has size zero, but element shape <unknown> is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: gradients/autoencoder/autoencoder/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGatherV3 = TensorArrayGatherV3[dtype=DT_FLOAT, element_shape=<unknown>, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/autoencoder/autoencoder/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGrad/TensorArrayGradV3, autoencoder/autoencoder/TensorArrayUnstack/range, gradients/autoencoder/autoencoder/while/TensorArrayReadV3/Enter_1_grad/b_acc_3)]]
	 [[Node: truediv/_111 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1957_truediv", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'gradients/autoencoder/autoencoder/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGatherV3', defined at:
  File "train-autoencoder.py", line 106, in <module>
    bidirectional=args.bidirectional)
  File "/home/dpi/Documentos/Gustavo/autoencoder/src/autoencoder.py", line 163, in __init__
    self._create_training_tensors()
  File "/home/dpi/Documentos/Gustavo/autoencoder/src/autoencoder.py", line 200, in _create_training_tensors
    gradients, v = zip(*optimizer.compute_gradients(self.loss))
  File "/home/dpi/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 526, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/home/dpi/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 494, in gradients
    gate_gradients, aggregation_method, stop_gradients)
  File "/home/dpi/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 636, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "/home/dpi/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 385, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/home/dpi/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 636, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "/home/dpi/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_grad.py", line 186, in _TensorArrayScatterGrad
    grad = g.gather(indices)
  File "/home/dpi/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 910, in gather
    return self._implementation.gather(indices, name=name)
  File "/home/dpi/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 305, in gather
    element_shape=element_shape)
  File "/home/dpi/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 6018, in tensor_array_gather_v3
    flow_in=flow_in, dtype=dtype, element_shape=element_shape, name=name)
  File "/home/dpi/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/dpi/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/dpi/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

...which was originally created as op 'autoencoder/autoencoder/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3', defined at:
  File "train-autoencoder.py", line 106, in <module>
    bidirectional=args.bidirectional)
  File "/home/dpi/Documentos/Gustavo/autoencoder/src/autoencoder.py", line 90, in __init__
    scope=self.scope)
  File "/home/dpi/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py", line 627, in dynamic_rnn
    dtype=dtype)
  File "/home/dpi/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py", line 754, in _dynamic_rnn_loop
    for ta, input_ in zip(input_ta, flat_input))
  File "/home/dpi/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py", line 754, in <genexpr>
    for ta, input_ in zip(input_ta, flat_input))
  File "/home/dpi/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/tf_should_use.py", line 118, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
  File "/home/dpi/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 944, in unstack
    return self._implementation.unstack(value, name=name)
  File "/home/dpi/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/tf_should_use.py", line 118, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
  File "/home/dpi/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 333, in unstack
    indices=math_ops.range(0, num_elements), value=value, name=name)
  File "/home/dpi/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/tf_should_use.py", line 118, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
  File "/home/dpi/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 349, in scatter
    name=name)
  File "/home/dpi/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 6590, in tensor_array_scatter_v3
    flow_in=flow_in, name=name)
  File "/home/dpi/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)

UnimplementedError (see above for traceback): TensorArray has size zero, but element shape <unknown> is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: gradients/autoencoder/autoencoder/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGatherV3 = TensorArrayGatherV3[dtype=DT_FLOAT, element_shape=<unknown>, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/autoencoder/autoencoder/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGrad/TensorArrayGradV3, autoencoder/autoencoder/TensorArrayUnstack/range, gradients/autoencoder/autoencoder/while/TensorArrayReadV3/Enter_1_grad/b_acc_3)]]
	 [[Node: truediv/_111 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1957_truediv", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
